### ISSUE TITLE
Usage is unclear

### ISSUE THREAD

**Issue by engineeror** [bbbbbr/gimp-rom-bin#1]
I get `00 00 FF 00 81 00 FF 00 C3 00 FF 00 E7 00 E7 00` which is white bars in grey background but it should be black bars in white background. Check here http://www.huderlem.com/demos/gameboy2bpp.html GIMP 2.10.8 color mode 1bit, RGB, greyscale - makes no difference at all

**Comment by engineeror** [comment]
nevermind, figured it out. it's too hard to explain the process but you gotta create 4 color pallete starting with white ending with black or whatever 4 colorus you wish. then apply the pallete

**Comment by bbbbbr** [comment]
The image you see will depend on the palette used in Gimp to create the image, as well as the palette that the Gameboy is configured with. 

So Yes, I think you are on the right track.

The actual sprite data itself will not change if you alter the palettes, since the indexed color entries are always encoded the same way. But the palette used can influence which color index you choose for a given pixel. So it is best to start out using the palette the Gameboy or emulator will be using, and create the images from there.

Hope this helps.
